import { Poppins } from "next/font/google";
import "@/components/ui/globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} w-full h-full bg-bg text-white`}>
        {children}
      </body>
    </html>
  );
}
